theme: jekyll-theme-minimal
title: ADA Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: The project
    url: project
    url: coronawiki_part
  - title: Our team
    url: team
