theme: jekyll-theme-minimal
title: "Trendy topics during lockdown: Netflix and chill or dream of escape ?"
description: An ADA project by the DataMinors
show_downloads: True
navigation:
  - title: The project
    url: project
  - title: Our team
    url: team
