theme: jekyll-theme-minimal
title: LE TITRE QU'ON A TOUJOURS PAS TROUVE
description: An ADA project by the DataMinors
show_downloads: True
navigation:
  - title: The project
    url: project
  - title: Our team
    url: team
